'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { Activity, ArrowUpRight, Beaker, BookOpen, Boxes, Check, ChevronRight, Database, Download, FileCheck, FlaskConical, GitBranch, Layers, Loader2, Plus, Search, ShieldCheck } from 'lucide-react';

type Project = { id: string; name: string; description: string };
type Artifact = { id: string; kind: string; parents: string[]; created_at: string; filename?: string; rows?: number; columns?: string[]; dataset_id?: string; audit_id?: string; assignments?: string[]; result?: Record<string, any>; config?: Record<string, any>; status?: string; model?: string; error?: string; reason?: string; record?: any; title?: string; activity?: string; inputs?: string[]; outputs?: string[] };
type Job = { id: string; kind: string; state: string; error?: string; result_id?: string };
const nav = [
  ['projects', 'Projects', Boxes], ['evidence', 'Evidence', BookOpen], ['dataset-audit', 'Dataset audit', ShieldCheck],
  ['split-designer', 'Split designer', GitBranch], ['benchmark', 'Benchmarks', Activity], ['failure-memory', 'Failure memory', FlaskConical],
  ['provenance', 'Provenance', Layers], ['report', 'Reports', FileCheck]
] as const;
const descriptions: Record<string, string> = {
  projects: 'One workspace. Every step of your scientific ML workflow.', evidence: 'Keep source documents and their traceable extraction records together.',
  'dataset-audit': 'Understand your data before trusting your model.', 'split-designer': 'Make the partition match the scientific question.',
  benchmark: 'Evaluate a baseline on your frozen, scientifically meaningful partition.', 'failure-memory': 'Preserve unsuccessful runs and the lessons behind them.',
  provenance: 'Follow the chain from source data to reported results.', report: 'Package the data, configuration and results needed to reproduce your work.'
};
const sourceDefault = { citation: 'Workbench synthetic demonstration', url: 'Not applicable: generated fixture', license: 'CC0-1.0', data_kind: 'synthetic', transformations: 'Deterministic toy fixture; no empirical claims.' };
const auditDefault = { numeric_columns: ['temperature', 'response'], feature_columns: ['temperature'], target_column: 'response', provenance_columns: ['source_id', 'group_id'] };
const splitDefault = { strategy: 'composition', columns: ['group_id'], group_columns: ['group_id'], target_column: 'response', validation_size: 0.2, test_size: 0.2, seed: 42 };
const benchDefault = { target: 'response', numeric_features: ['temperature'], categorical_features: [], row_id: 'row_id', group_columns: ['group_id'], units: { temperature: 'kelvin', response: 'dimensionless' }, independence_unit: 'Generated family', independence_status: 'synthetic', independence_rationale: 'Each family is held entirely within a partition.', generalization: 'Held-out generated families only.', limitations: ['Synthetic software fixture; not experimental evidence.'], domain: 'materials', accepted_warnings: {}, model: 'ridge', seed: 0 };

async function api(path: string, init?: RequestInit) {
  const response = await fetch(`/api/${path}`, init);
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || data.detail || 'Request failed');
  return data;
}
function JsonBox({ value }: { value: unknown }) { return <details className="json"><summary>Inspect complete artifact</summary><pre>{JSON.stringify(value, null, 2)}</pre></details>; }
function Editor({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return <label className="field">{label}<textarea className="code" value={value} rows={9} onChange={e => onChange(e.target.value)} spellCheck={false} /></label>;
}
function Badge({ state }: { state: string }) { return <span className={`badge ${state}`}>{state.replaceAll('_', ' ')}</span>; }

export default function Workbench({ view }: { view: string }) {
  const [projects, setProjects] = useState<Project[]>([]), [pid, setPid] = useState('');
  const [artifacts, setArtifacts] = useState<Artifact[]>([]), [jobs, setJobs] = useState<Job[]>([]);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [name, setName] = useState(''), [description, setDescription] = useState('');
  const [file, setFile] = useState<File | null>(null), [title, setTitle] = useState('');
  const [source, setSource] = useState(JSON.stringify(sourceDefault, null, 2));
  const [auditConfig, setAuditConfig] = useState(JSON.stringify(auditDefault, null, 2));
  const [splitConfig, setSplitConfig] = useState(JSON.stringify(splitDefault, null, 2));
  const [benchConfig, setBenchConfig] = useState(JSON.stringify(benchDefault, null, 2));
  const [datasetId, setDatasetId] = useState(''), [splitId, setSplitId] = useState(''), [runId, setRunId] = useState('');
  const [reason, setReason] = useState(''), [uncertainty, setUncertainty] = useState(''), [query, setQuery] = useState('');
  const selectedProject = projects.find(p => p.id === pid);
  const kinds = (kind: string) => artifacts.filter(a => a.kind === kind);
  const datasets = kinds('dataset'); const selectedDataset = datasets.find(d => d.id === datasetId) || datasets.at(-1);
  const audits = kinds('audit').filter(a => a.dataset_id === selectedDataset?.id);
  const partitions = kinds('split').filter(a => a.dataset_id === selectedDataset?.id);
  const selectedSplit = partitions.find(s => s.id === splitId) || partitions.at(-1);
  const runs = kinds('benchmark'); const selectedRun = runs.find(r => r.id === runId) || runs.at(-1);
  const active = jobs.some(j => ['queued', 'running'].includes(j.state));

  const refresh = useCallback(async () => {
    if (!pid) return;
    const [a, j] = await Promise.all([api(`projects/${pid}/artifacts`), api(`projects/${pid}/jobs`)]);
    setArtifacts(a); setJobs(j);
  }, [pid]);
  useEffect(() => { api('projects').then(p => { setProjects(p); const saved = localStorage.getItem('sciml-project'); setPid(p.find((x: Project) => x.id === saved)?.id || p[0]?.id || ''); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { setArtifacts([]); setJobs([]); setDatasetId(''); setSplitId(''); setRunId(''); if (pid) localStorage.setItem('sciml-project', pid); refresh().catch(e => setError(e.message)); }, [pid, refresh]);
  useEffect(() => { if (!pid) return; const timer = setInterval(() => refresh().catch(e => setError(e.message)), 2500); return () => clearInterval(timer); }, [pid, refresh]);
  async function act(fn: () => Promise<void>) {
    setBusy(true); setError(''); setNotice('');
    try { await fn(); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Operation failed'); } finally { setBusy(false); }
  }
  async function submit(kind: string, payload: object = {}) {
    await api(`projects/${pid}/${kind}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify(payload) });
    setNotice('Job queued. You can follow its progress below.');
  }
  const disabled = busy || !pid;
  const datasetSelect = <label className="field">Dataset<select value={selectedDataset?.id || ''} onChange={e => { setDatasetId(e.target.value); setSplitId(''); }}><option value="" disabled>Select a dataset</option>{datasets.map(d => <option key={d.id} value={d.id}>{d.filename} · {d.rows} rows</option>)}</select></label>;

  return <div className="app-shell">
    <aside className="sidebar"><Link href="/" className="brand"><span className="brand-icon"><Beaker size={22}/></span><span>SciML<span className="brand-sub">WORKBENCH</span></span></Link>
      <div className="workspace-label">WORKSPACE</div><div className="workspace-picker"><span className="avatar">K</span><div>Research workspace<small>Local research environment</small></div></div>
      <nav aria-label="Main navigation">{nav.map(([key, label, Icon]) => <Link key={key} href={`/${key}`} className={key === view ? 'nav-item selected' : 'nav-item'}><Icon size={18}/>{label}{key === view && <ChevronRight size={14} className="nav-chevron"/>}</Link>)}</nav>
      <div className="sidebar-note"><span className="dot"/> Traceability by design<p>Independent tools.<br/>Connected scientific workflows.</p><span className="version">MVP · v0.1.0</span></div>
    </aside>
    <div className="main-shell"><header className="topbar"><span>Workspace <ChevronRight size={14}/> <strong>{nav.find(n => n[0] === view)?.[1]}</strong></span><div className="top-right"><span className="private"><ShieldCheck size={14}/> Local workspace</span><span className="avatar small">K</span></div></header>
      <main><div className="page-heading"><div className="eyebrow">SCIENTIFIC MACHINE LEARNING</div><div className="heading-row"><div><h1>{nav.find(n => n[0] === view)?.[1]}</h1><p>{descriptions[view]}</p></div><span className="outline-tag"><span className="dot"/> Four tools, one workflow</span></div></div>
      {error && <div role="alert" className="alert error">{error}</div>}{notice && <div role="status" className="alert success"><Check size={17}/>{notice}</div>}
      <div className="project-bar"><label>Active project<select aria-label="Active project" value={pid} onChange={e => setPid(e.target.value)}><option value="" disabled>Select or create a project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><span>{selectedProject?.description || 'Your data and results stay grouped by project.'}</span></div>

      {view === 'projects' && <>
        <div className="hero"><div><div className="eyebrow">FROM DATA TO DEFENSIBLE RESULTS</div><h2>Build confidence in<br/>every scientific result.</h2><p>Connect evidence, audit your data, design a meaningful split,<br/>and preserve what you learn along the way.</p><Link className="button light" href="/dataset-audit">Start with a dataset <ArrowUpRight size={16}/></Link></div><div className="hero-art" aria-hidden="true"><div className="orbit"><Database/><span className="orbit-node n1"><BookOpen/></span><span className="orbit-node n2"><GitBranch/></span><span className="orbit-node n3"><Activity/></span><span className="orbit-node n4"><FlaskConical/></span></div><span className="art-label">CONNECTED RESEARCH</span></div></div>
        <div className="stats">{[['Datasets', datasets.length, Database], ['Audits', kinds('audit').length, ShieldCheck], ['Benchmark runs', runs.length, Activity], ['Lessons saved', kinds('failure').length, FlaskConical]].map(([label, count, Icon]) => { const I = Icon as typeof Database; return <div className="stat" key={String(label)}><I size={19}/><strong>{String(count)}</strong><span>{String(label)}</span></div>; })}</div>
        <div className="two-col"><section className="panel"><div className="section-heading"><h2>Create a project</h2><Plus size={18}/></div><p className="muted">A home for a dataset, its evidence and reproducible runs.</p><form onSubmit={e => { e.preventDefault(); act(async () => { const p = await api('projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, description }) }); setProjects([p, ...projects]); setPid(p.id); setName(''); setDescription(''); setNotice('Project created. Upload your first dataset.'); }); }}><label className="field">Project name<input required maxLength={160} placeholder="e.g. Electrolyte screening study" value={name} onChange={e => setName(e.target.value)}/></label><label className="field">Research question<textarea placeholder="What do you want this model to generalize to?" value={description} onChange={e => setDescription(e.target.value)} maxLength={2000}/></label><button disabled={busy} type="submit"><Plus size={16}/>Create project</button></form></section>
        <section className="panel"><h2>Your workflow</h2><p className="muted">Each step keeps a link to the artifacts that came before it.</p>{[['dataset-audit','01','Upload & audit','Inspect quality, provenance and leakage.'],['split-designer','02','Design a scientific split','Keep independent units together.'],['benchmark','03','Run a baseline','Evaluate on frozen partitions.'],['failure-memory','04','Capture & reproduce','Record lessons and export your report.']].map(([url,n,t,d]) => <Link key={n} className="workflow-step" href={`/${url}`}><span>{n}</span><div><strong>{t}</strong><small>{d}</small></div><ChevronRight size={16}/></Link>)}</section></div>
      </>}

      {view === 'dataset-audit' && <><div className="two-col"><section className="panel"><h2>Upload a CSV</h2><p className="muted">UTF-8 · up to 10 MiB · 20,000 rows. Original bytes are preserved.</p><label className="dropzone"><Database size={26}/><strong>{file?.name || 'Choose your dataset'}</strong><span>CSV with unique column names</span><input aria-label="CSV file" type="file" accept=".csv" onChange={e => setFile(e.target.files?.[0] || null)}/></label><Editor label="Source metadata · replace the demo declarations for your data" value={source} onChange={setSource}/><button disabled={disabled || !file} onClick={() => act(async () => { const src = JSON.parse(source); await api(`projects/${pid}/datasets`, { method: 'POST', headers: { 'Content-Type': 'text/csv', 'X-Filename': file!.name, 'X-Source': JSON.stringify(src) }, body: file }); setNotice('Dataset uploaded with its source metadata.'); })}>Upload dataset <ArrowUpRight size={16}/></button></section><section className="panel"><h2>Run ChemData Auditor</h2><p className="muted">Declare your target, available features and provenance columns.</p>{datasetSelect}<Editor label="Audit configuration" value={auditConfig} onChange={setAuditConfig}/><button disabled={disabled || !selectedDataset} onClick={() => act(() => submit('audit', { dataset_id: selectedDataset!.id, config: JSON.parse(auditConfig) }))}><ShieldCheck size={16}/>Run audit</button></section></div>
        {audits.map(a => <section className="panel result" key={a.id}><div className="section-heading"><h2>Audit findings</h2><Badge state="completed"/></div>{!a.result?.findings?.length && <p>No findings for the configured checks. This does not certify scientific validity.</p>}{a.result?.findings?.map((f: any, i: number) => <div className="finding" key={i}><Badge state={f.severity}/><div><strong>{f.code}</strong><p>{f.message}</p><small>{f.action || f.recommendation}</small></div></div>)}<JsonBox value={a}/></section>)}</>}

      {view === 'split-designer' && <><div className="two-col"><section className="panel"><h2>Define the holdout</h2>{datasetSelect}<p className="muted">The latest audit of this dataset is linked automatically. Configuration is passed directly to SciSplit.</p><Editor label="SciSplit configuration" value={splitConfig} onChange={setSplitConfig}/><button disabled={disabled || !audits.length} onClick={() => act(() => submit('split', { dataset_id: selectedDataset!.id, audit_id: audits.at(-1)!.id, config: JSON.parse(splitConfig) }))}><GitBranch size={16}/>Generate partition</button>{!audits.length && <p className="hint">Upload a dataset and complete an audit first.</p>}</section><section className="panel"><h2>Partition balance</h2><p className="muted">Rows are shown in original CSV order. Grouping and diagnostics come from SciSplit.</p>{selectedSplit ? <><div className="partition-bar">{['train','validation','test','excluded'].map(p => { const count = selectedSplit.assignments!.filter(x => x === p).length; return count > 0 && <div key={p} className={p} style={{flex: count}} title={`${p}: ${count}`}>{count}</div>; })}</div><div className="legend">{['train','validation','test','excluded'].map(p => <span key={p}><i className={p}/>{p} · {selectedSplit.assignments!.filter(x => x === p).length}</span>)}</div><div className="row-grid">{selectedSplit.assignments!.slice(0,400).map((p,i) => <span className={p} key={i} title={`Row ${i}: ${p}`}/>)}</div><p className="hint">Showing the first {Math.min(400,selectedSplit.assignments!.length)} rows. Download the report for every assignment.</p><JsonBox value={selectedSplit}/></> : <div className="empty"><GitBranch size={36}/><h3>Your partition will appear here</h3><p>Start with an explicit scientific holdout.</p></div>}</section></div></>}

      {view === 'benchmark' && <><div className="two-col"><section className="panel"><h2>Configure a baseline</h2>{datasetSelect}<label className="field">Frozen split<select value={selectedSplit?.id || ''} onChange={e => setSplitId(e.target.value)}><option value="" disabled>Select a partition</option>{partitions.map(s => <option key={s.id} value={s.id}>{s.config?.strategy} · {s.id.slice(0,8)}</option>)}</select></label><Editor label="Task card declarations" value={benchConfig} onChange={setBenchConfig}/><button disabled={disabled || !selectedSplit} onClick={() => act(() => submit('benchmark', { ...JSON.parse(benchConfig), dataset_id: selectedDataset!.id, split_id: selectedSplit!.id }))}><Activity size={16}/>Run benchmark</button></section><section className="panel"><h2>Evaluation protocol</h2><div className="protocol"><ShieldCheck size={24}/><h3>Admission before evaluation</h3><p>ChemE Benchmarks validates the dataset, units, independent groups and frozen split before training.</p><p>Preprocessing uses training data. Hyperparameter selection uses validation data. Final scores use held-out test data.</p><p>Errors block admission. Warning acceptance requires your written scientific justification.</p><span className="outline-tag">Local task · no official leaderboard claim</span></div></section></div>{runs.map(r => <section className="panel result" key={r.id}><div className="section-heading"><h2>{r.model} baseline</h2><Badge state={r.status || ''}/></div>{r.error && <p className="alert error">{r.error}</p>}{r.result?.metrics && <div className="metrics">{Object.entries(r.result.metrics.test || {}).filter(([,v]) => typeof v === 'number').map(([k,v]) => <div key={k}><span>{k}</span><strong>{Number(v).toPrecision(4)}</strong></div>)}</div>}<JsonBox value={r}/><Link className="text-link" href="/failure-memory">Record an unsuccessful outcome <ArrowUpRight size={14}/></Link></section>)}</>}

      {view === 'evidence' && <><section className="panel"><h2>Add a source document</h2><p className="muted">Scientific Evidence Engine preserves the original PDF, page text, page hashes and user-supplied metadata. Scanned pages may have no extractable text.</p><div className="two-col"><label className="field">Document title<input value={title} onChange={e => setTitle(e.target.value)} placeholder="Paper or internal research note"/></label><label className="field">PDF file<input type="file" accept=".pdf" onChange={e => setFile(e.target.files?.[0] || null)}/></label></div><button disabled={disabled || !title.trim() || !file} onClick={() => act(async () => { await api(`projects/${pid}/evidence`, { method: 'POST', headers: { 'X-Title': title, 'Content-Type':'application/pdf', 'Idempotency-Key':crypto.randomUUID() }, body: file }); setNotice('Evidence ingestion queued.'); })}><BookOpen size={16}/>Ingest document</button></section>{kinds('evidence').map(a => <section className="panel result" key={a.id}><h2>{a.title}</h2><p className="muted">{a.result?.page_count} pages · metadata supplied by researcher</p><JsonBox value={a}/><a className="text-link" href={`/api/projects/${pid}/artifacts/${a.id}/download`}>Download source bundle <Download size={14}/></a></section>)}</>}

      {view === 'failure-memory' && <><section className="panel"><h2>Save a lesson from a run</h2><p className="muted">A completed model can still miss your scientific objective. Explain your assessment; computational outcomes are labeled separately from physical experiments.</p><label className="field">Benchmark run<select value={selectedRun?.id || ''} onChange={e => setRunId(e.target.value)}><option value="" disabled>Select a run</option>{runs.map(r => <option key={r.id} value={r.id}>{r.model} · {r.status} · {r.id.slice(0,8)}</option>)}</select></label><div className="two-col"><label className="field">Why was this run unsuccessful?<textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="What failed, or what objective was not met?"/></label><label className="field">Uncertainty and limits<textarea value={uncertainty} onChange={e => setUncertainty(e.target.value)} placeholder="What remains unknown? Separate observed facts from suspected causes."/></label></div><button disabled={disabled || !selectedRun || !reason.trim() || !uncertainty.trim()} onClick={() => act(() => submit('failure', { benchmark_id:selectedRun!.id, reason, uncertainty_notes:uncertainty }))}><FlaskConical size={16}/>Save to Failure Memory</button></section><div className="search"><Search size={18}/><input aria-label="Search saved lessons" placeholder="Search saved lessons in this project…" value={query} onChange={e => setQuery(e.target.value)}/></div>{kinds('failure').filter(f => JSON.stringify(f).toLowerCase().includes(query.toLowerCase())).map(f => <section className="panel result" key={f.id}><Badge state="recorded"/><h3>{f.reason}</h3><JsonBox value={f}/></section>)}</>}

      {view === 'provenance' && <section className="panel"><h2>Artifact lineage</h2><p className="muted">Immutable artifact IDs connect each operation to its exact inputs. Source assertions remain user-supplied.</p>{kinds('provenance').length ? kinds('provenance').map(a => <div className="lineage" key={a.id}><span className="lineage-icon"><Layers size={16}/></span><div><strong>{a.activity}</strong><small>{new Date(a.created_at).toLocaleString()}</small><div className="lineage-links"><span>Inputs: {a.inputs?.map(x => x.slice(0,8)).join(', ') || 'Original upload'}</span><ChevronRight size={14}/><span>Outputs: {a.outputs?.map(x => x.slice(0,8)).join(', ')}</span></div><JsonBox value={a}/></div></div>) : <div className="empty"><Layers size={36}/><h3>No lineage yet</h3><p>Upload data or evidence to begin.</p></div>}</section>}

      {view === 'report' && <section className="panel"><div className="report-icon"><FileCheck size={30}/></div><h2>A reproducible record of your research</h2><p className="muted">Export original data, source evidence, configurations, partition assignments, predictions, metrics, failure records, package pins and a SHA-256 manifest.</p><div className="report-checks">{['Original inputs & provenance','Frozen split assignments','Audits & benchmark results','Failure records & replay instructions'].map(x => <span key={x}><Check size={16}/>{x}</span>)}</div><button disabled={disabled || active || !artifacts.length} onClick={() => act(() => submit('report'))}><FileCheck size={16}/>Generate report</button>{active && <p className="hint">Wait for active jobs to finish before exporting.</p>}{kinds('report').map(r => <div className="download-row" key={r.id}><div><strong>Reproducible research bundle</strong><small>{new Date(r.created_at).toLocaleString()}</small></div><a className="button" href={`/api/projects/${pid}/artifacts/${r.id}/download`}><Download size={16}/>Download ZIP</a></div>)}</section>}

      {view !== 'projects' && !pid && <div className="alert">Create a project to start this workflow. <Link href="/projects">Go to projects →</Link></div>}
      {jobs.length > 0 && <section className="panel jobs"><div className="section-heading"><h2>Job activity</h2>{active && <span className="working"><Loader2 size={15} className="spin"/>Processing</span>}</div>{jobs.slice(0,8).map(j => <div className="job" key={j.id}><span><strong>{j.kind}</strong><small>{j.id.slice(0,8)}</small></span><div>{j.error && <p className="job-error">{j.error}</p>}<Badge state={j.state}/></div></div>)}</section>}
      <footer>SCIML WORKBENCH<span>Evidence → data → evaluation → learning</span></footer>
      </main></div></div>;
}
