export type HelpTopic = { title:string; words:string; answer:string; href:string; views:string[] };
export const HELP_TOPICS: HelpTopic[] = [
  {title:'Move around the workflow canvas',words:'pan mouse drag scroll zoom fit plus minus arrow grip move',views:['workflows'],href:'/docs/research-workflows',answer:'Hold the mouse down on empty canvas space and drag to pan. Drag a step by its grip to move it instead. Focus the canvas and use arrow keys to pan with the keyboard. + and − change the zoom; Fit brings the graph into view.'},
  {title:'Cancel or save a workflow',words:'cancel creation new mistake discard all workflows save copy template archive',views:['workflows'],href:'/docs/research-workflows',answer:'Cancel creation closes a new draft without saving it. If you changed the draft, confirm that you want to discard those changes. Save validates the graph. Save a copy keeps the original template intact. All workflows returns to the catalog; Archive removes a saved custom workflow from the catalog while preserving existing executions.'},
  {title:'Connect steps and choose link types',words:'ports connect output input signal artifact edge remove connection delete',views:['workflows'],href:'/docs/research-workflows',answer:'Click an output port, then another step’s input port. You can also choose Output port, Connection type and Connect to step in the inspector, then press Connect. Signal links only control execution order; Artifacts links carry retained research results. Cancel abandons a pending link. The × beside a connection removes it from the draft.'},
  {title:'What each workflow step means',words:'trigger research tool condition yes no branch join repeat finish iterations rounds',views:['workflows'],href:'/docs/research-workflows',answer:'Trigger starts the graph. Research assigns a task to agents. Research tool applies a saved tool. Condition chooses a yes/no path; connect both. Join waits for the incoming paths, including skipped ones. Repeat runs 1–5 rounds. Finish collects results. Click a step to change its name, instructions, assignment or settings. Delete step also removes its connections.'},
  {title:'Run, schedule, or stop research',words:'run start daily schedule stop cancel parallel concurrency approval review plan',views:['workflows','stress-test'],href:'/docs/research-workflows',answer:'Save first, then Run to choose the question and project inputs. Start research launches it. Parallel research steps limits concurrent work to 1–3 steps. Daily requires explicit opt-in and runs at most once per UTC day when the scheduler wakes. Stop schedule prevents future runs; Stop workflow cancels the current children. Open research shows results and any questions or plans awaiting your review.'},
  {title:'Choose agents and teams',words:'assign lead team skills create agent name specialist pi default only exclusive copy',views:['agent-market','ask','projects'],href:'/docs/working-with-agents',answer:'Create agent chooses its name, role, instructions, skills and tools. Customize a copy preserves a built-in original. Create team chooses its members and a lead from those members. Assign to selects an agent or team for a request; Only use this team keeps the roster exclusive. Use as project default saves the choice for future requests. Existing runs keep their original roster.'},
  {title:'Create a reusable tool',words:'tools market instructions capabilities create custom skill plugin prompt generate draft ai',views:['tools','agent-market'],href:'/docs/research-tools',answer:'Choose Create with AI, describe the goal, inputs and desired output, then Generate draft. Review and edit the suggested instructions and capabilities before Save tool. Generation shows elapsed progress and can be stopped. AI generation needs a selected project and configured provider. The demo uses a prewritten sample. Or choose Create tool, name it, describe the output, and write instructions. Select the integrated capabilities it may use. Attach it to a custom agent or use it in a Research tool workflow step. These are reusable instructions with bounded capabilities, not uploaded programs or arbitrary network integrations.'},
  {title:'Stress-test an idea, paper, or result',words:'stress test council reviewer criticize critique quality paper idea results confidence',views:['stress-test'],href:'/docs/stress-testing',answer:'Choose what you want challenged, describe the claim, and select supporting files or retained results. Specialist review uses one curated reviewer. Independent council runs methods, statistics and evidence reviewers separately with fixed rubrics. Compare their specific concerns, evidence, uncertainty and resolving tests. They use the workspace’s configured model; agreement is not independent proof or a peer-review decision.'},
  {title:'Bring files and ask a question',words:'upload attach csv pdf send project question files prompt',views:['ask','projects'],href:'/docs/getting-started',answer:'Choose a project at the top or create one in Projects. In Ask, attach CSV datasets or text-layer PDFs and describe your research question. Show me the plan first lets you review before execution. Send starts the work. For a stress test, you can also attach files directly in Stress test.'},
  {title:'AI availability and access',words:'unavailable error configuration key provider deepseek permissions support login',views:[],href:'/docs/troubleshooting',answer:'If the assistant is unavailable, the workspace owner must configure the provider and enable agents. File access follows project permissions. Product guides still work without AI. Never paste passwords or API keys into a conversation. Product Support cannot change configuration or access research attachments.'},
];
export function helpTopics(question:string, view:string): HelpTopic[] {
  const words=question.toLowerCase().match(/[a-z0-9]+/g)?.filter(w=>w.length>2)??[];
  return HELP_TOPICS.map((topic,index)=>({topic,index,score:words.length ? words.reduce((n,w)=>n+Number(`${topic.title} ${topic.words}`.toLowerCase().includes(w)),0) : Number(topic.views.includes(view))*2}))
    .sort((a,b)=>b.score-a.score||a.index-b.index).slice(0,3).map(v=>v.topic);
}
