import type { PixelVariant } from '../components/pixel-scene';

export type GuideSection = { title: string; paragraphs: string[]; steps?: string[]; note?: string };
export type Guide = { slug: string; title: string; description: string; sections: GuideSection[]; tool: [string, string]; source: string };
export const guides: Guide[] = [
  {
    slug: 'getting-started', title: 'Your first investigation', description: 'Sign in, bring a file, ask a useful question, and inspect the answer.', tool: ['Open Ask', '/ask'], source: 'README.md',
    sections: [
      { title: 'Before you begin', paragraphs: ['SciML Workbench is a private research workspace. Use the username and password provided by the person who runs your installation. There is no public account signup. The owner configures the AI provider, available tools, and access policy.', 'You can use the manual scientific tools without an enabled assistant. If Ask reports that agents are unavailable, follow the data and evaluation guides or ask your workspace owner to finish agent setup.'] },
      { title: 'Ask your first question', paragraphs: ['Start small: understand a dataset before asking for a complete modeling study. A CSV spreadsheet or PDF paper is enough to begin.'], steps: ['Open Ask and attach a CSV or PDF with the paperclip, or drag a file into the composer.', 'Write a specific goal, such as “Check this spreadsheet for missing values and duplicate rows. Explain the problems. Do not build a model.”', 'Turn on “Show me the plan first” when you want a checkpoint before the investigation proceeds.', 'Send with Enter or the arrow button. Use Shift + Enter to add a new line. A first request can create its own project; you can select an existing project for related work.'] },
      { title: 'Follow the work', paragraphs: ['The request shows its current phase and activity. “Needs your input” means there is a question or plan to review. “Crunching numbers” means a calculation is running. A queued request has been accepted but has not started yet.', 'Open the research team activity to inspect the available coordinator and specialist updates. Simple questions may be answered directly; not every request requires a team of specialists or a scientific calculation.'] },
      { title: 'Read the answer, then the evidence', paragraphs: ['Read the response alongside its saved results. Follow the source references, inspect warnings, and check which files and methods were used. A completed run is not a guarantee that a scientific conclusion is correct.', 'Ask a follow-up in the same project to retain relevant context. Before sending, check the file chips: selected earlier files are included, and you can switch off any that should be left out.'], note: 'For a safe first exercise, use examples/demo.csv from the repository. It is synthetic demonstration data, not empirical evidence.' },
    ],
  },
  {
    slug: 'projects-and-data', title: 'Projects, files, and data', description: 'Organize an investigation and preserve the original materials behind it.', tool: ['Open Projects', '/projects'], source: 'docs/intake.md',
    sections: [
      { title: 'Choose the right project', paragraphs: ['A project groups research materials, datasets, jobs, saved results, and their history. Keep one investigation in one project so that you can trace how a result was produced. Switch projects from the workspace picker; check the selected project before uploading or starting a calculation.', 'Ask offers a prompt-first path. Detailed request exposes a research request with explicit inputs and controls. The advanced views let you perform individual scientific steps yourself.'] },
      { title: 'Attach a CSV', paragraphs: ['A CSV upload creates a preserved research material and a dataset artifact. The original bytes remain unchanged. Derived audits, splits, and benchmarks become separate artifacts linked to that dataset.', 'Use UTF-8 CSV with unique, nonblank column names, consistent row widths, and at least three data rows. The supported intake allows up to 200 columns; row and upload-size limits depend on the server configuration.'], steps: ['Choose the dataset file and inspect its columns.', 'When supplying source metadata, enter the actual citation, source URL, license, data type, and transformations you know.', 'Leave unknown facts unknown. Use the synthetic-demo declaration only for the bundled demonstration file.', 'Upload, then verify the material and dataset appear in the selected project.'] },
      { title: 'Attach and extract a PDF', paragraphs: ['A PDF attachment preserves the original document. Text extraction is a separate job: accepting an upload does not mean extraction succeeded. Review its job status and extracted passages before relying on the paper as evidence.', 'Scanned papers may not provide usable text. OCR is not part of the documented ingestion workflow. An extraction failure does not remove the original attachment.'] },
      { title: 'Understand access and provenance', paragraphs: ['An uploaded file is not automatically permission for every agent to read it. The workspace policy controls allowed projects, materials, artifacts, tools, and outbound access. Some single-operator installations explicitly enable automatic policy grants.', 'Provenance records the connections between inputs and derived results. Open History to answer “Which dataset, settings, and earlier steps produced this?” Source metadata is an assertion to verify, not proof that data is scientifically suitable.'] },
    ],
  },
  {
    slug: 'working-with-agents', title: 'Working with your AI lab group', description: 'Write clear requests, review plans, and control an investigation as it runs.', tool: ['Open Research', '/research'], source: 'docs/agent-operator-guide.md',
    sections: [
      { title: 'Give the team a bounded goal', paragraphs: ['Describe the question, relevant files, desired output, and constraints. “Audit these measurements; do not fit a model” is easier to inspect than “analyze everything.” State the target variable and the scientific unit of independence when they matter.', 'The coordinator can answer directly or delegate bounded tasks to specialists. Available tools and models are set by the workspace owner; a model proposing an action does not establish that the action is supported or permitted.'] },
      { title: 'Review before continuing', paragraphs: ['Use the composer’s plan-review option to request a human checkpoint. When a run needs input, inspect the proposed steps and respond through the available review controls. Check the chosen files, intended methods, evaluation boundaries, and expected output.', 'Detailed request provides the research view when you need to choose inputs and limits explicitly. The simpler Ask view and the detailed view refer to the same underlying project work.'] },
      { title: 'Pause, resume, or stop', paragraphs: ['Use the controls shown for the current run state. Pausing prevents new work from starting; already running work may need to settle. Resume when you are ready to continue. Cancel when the request should end, then wait for its state to confirm the stop.', 'Completed results remain available even when a later step fails or a request is stopped. “Partly done” means some work finished but the full goal was not satisfied. Inspect what is present before making another request.'] },
      { title: 'Limits and provider setup', paragraphs: ['DeepSeek and Anthropic adapters are implemented. The actual provider, coordinator model, specialist model, budgets, and allowed tools depend on the installation. These are server settings, not credentials to enter in a prompt.', 'Runs are bounded by policy and budgets. A budget stop or missing permission is a reason to review the request with the operator. Retrying the same goal does not itself repair the configuration. Keep API keys out of uploaded files and research goals.'], note: 'The operator guide in the repository covers model verification, pricing and usage bounds, policy grants, and enabling the agent runtime.' },
    ],
  },
  {
    slug: 'audit-and-evaluation', title: 'Audit, split, and evaluate', description: 'Move from raw data to a comparison you can explain and reproduce.', tool: ['Open Dataset Audit', '/dataset-audit'], source: 'README.md',
    sections: [
      { title: 'Audit before modeling', paragraphs: ['Open Check data (the dataset audit tool), select a dataset, and choose numeric, feature, target, and provenance columns. Run the audit and inspect its findings rather than treating successful execution as a clean bill of health.', 'Missing values, repeated rows, suspicious ranges, and provenance problems can change the question you should ask. Decide what each finding means for the study and record any corrective transformations as a new, traceable input.'] },
      { title: 'Design an honest holdout', paragraphs: ['Open Split data for the selected dataset. Choose a strategy that matches the intended generalization: new groups, later observations, or another supported boundary. Configure the grouping or strategy columns, validation and test sizes, and random seed.', 'Rows from the same experimental family may not be independent. If related observations cross partitions, a strong score can reflect overlap rather than useful prediction. Inspect partition membership and warnings before continuing.'], steps: ['State what a future unseen example represents.', 'Choose columns that capture shared experimental or source identity.', 'Generate the split and inspect partition counts and group overlap.', 'Keep the final test set out of model selection and record the intended evaluation protocol.'] },
      { title: 'Compare supported baselines', paragraphs: ['Open Test models with the dataset and split. Choose the target, feature columns, row identifier, supported model, units, and independence declarations. Supply the source metadata and scientific context required by admission checks.', 'Start with a simple supported baseline. Compare models under the same evaluation conditions. Inspect reported metrics together with sample counts, assumptions, warnings, and the generalization claim. The available scientific surface is determined by the installed packages.'] },
      { title: 'Keep the test boundary meaningful', paragraphs: ['Do not repeatedly use final test results to choose the winning model. The workbench records evaluation protocols and test exposure, and some test outputs require an explicit reveal.', 'When a benchmark is refused, read the stated reason. Missing source declarations, unresolved independence, or invalid inputs should be corrected at their source. A passing software check does not replace review of the study design.'] },
    ],
  },
  {
    slug: 'evidence-and-reports', title: 'Evidence, lessons, and reports', description: 'Trace claims to sources and carry useful results into the next experiment.', tool: ['Open Evidence', '/evidence'], source: 'docs/report-replay.md',
    sections: [
      { title: 'Inspect the source passage', paragraphs: ['Open Papers & sources to work with extracted paper content. Follow a reference to the document and passage it points to, then read enough surrounding context to judge whether it supports the claim.', 'Extraction can lose tables, equations, or layout. A referenced passage is a starting point for review, not an automatic endorsement of the assistant’s interpretation. Reopen the preserved original when the wording or context is unclear.'] },
      { title: 'Separate findings from claims', paragraphs: ['A calculation result, an interpretation of that result, and a statement from a paper are different kinds of evidence. Inspect the saved artifacts and claim references to understand which one supports an answer.', 'When the evidence is incomplete, retain that limitation. A narrow supported conclusion is more useful to the next investigation than an overconfident answer with a citation attached.'] },
      { title: 'Record unsuccessful attempts', paragraphs: ['Use Lessons learned to preserve what was tried, its outcome, the relevant inputs, and what you learned. Distinguish a failed calculation from a valid negative finding or a scientifically invalid comparison.', 'Before reusing an earlier lesson, check that its conditions match the new investigation. Saved context helps avoid repeating work; it does not make conclusions transferable to unrelated datasets.'] },
      { title: 'Export a reproducible record', paragraphs: ['Use Export to capture the project’s materials, results, and provenance in an archive. Manual project export requires the non-report jobs to be terminal, so wait for active work to finish or settle first.', 'The report captures a fixed snapshot. Later project changes do not alter that archive. Keep the archive with the study and use the repository’s report validation and replay guide when you need to inspect hashes, compatibility, or rerun supported scientific steps.'], note: 'Exports can contain original research materials and private scientific content. Share them according to the permissions for those materials.' },
    ],
  },
  {
    slug: 'troubleshooting', title: 'Troubleshooting and setup', description: 'Find the next useful step when uploads, agents, or calculations cannot continue.', tool: ['Open workspace', '/ask'], source: 'docs/runtime-setup.md',
    sections: [
      { title: 'Sign-in is unavailable', paragraphs: ['Use the web login supplied by your workspace owner. If the page says access is not configured, the operator must configure the server’s web credentials and public origin. This is separate from the backend API token and model-provider key.', 'After signing in, the application returns to the workspace page you originally requested. Signing out ends browser access; it does not delete your project work.'] },
      { title: 'A file will not upload', paragraphs: ['For CSV, check encoding, headers, row widths, and the configured size limit. For PDF, confirm it is a PDF file rather than another format with a renamed extension. Read the displayed validation error before resubmitting.', 'Check whether the original upload already succeeded before adding another copy. An extraction error belongs to the PDF-processing job and may be retried separately; it does not necessarily mean the attachment was lost.'] },
      { title: 'The assistant cannot start', paragraphs: ['Confirm that the intended project and input files are selected. Ask the operator whether agents are enabled, the provider is configured and verified, and the project and materials are covered by the execution policy.', 'A refusal can be caused by missing access, unavailable scientific capabilities, model configuration, or limits. Manual scientific tools remain an alternative when the required backend services are healthy. Do not paste API keys into the prompt to try to resolve access.'] },
      { title: 'A request is queued, disconnected, or stopped', paragraphs: ['Queued work needs an available worker. A connection interruption may hide current progress without stopping the server-side job. Reopen the project and inspect the latest saved state before submitting the same work again.', 'For a failed or partially completed request, inspect the safe error, activity, and available results. Use a retry control only when offered for that state. If the same failure recurs, record the project, run or job identifier, and displayed error for the operator.'] },
      { title: 'Run your own installation', paragraphs: ['The repository contains Docker Compose setup, migrations, backup and restore instructions, and an operator guide. Start with the runtime setup guide linked below, configure independent private secrets, and verify the manual workflow before enabling agents.', 'Upgrades to an existing installation require coordinated database and artifact backups. Consult the release and compatibility documentation before applying migrations or restoring an archive.'] },
    ],
  },
];

export type Post = { slug: string; title: string; description: string; category: string; art: PixelVariant; cover: PixelVariant; sections: GuideSection[]; guide: string };
export const posts: Post[] = [
  { slug: 'a-better-first-question', title: 'A better investigation starts with a smaller question.', description: 'How to turn “analyze my data” into a useful first conversation with your AI lab group.', category: 'Guide', art: 'bloom', cover: 'lens', guide: 'getting-started', sections: [
    { title: 'Give the first step a finish line', paragraphs: ['A broad request leaves many decisions unstated: what counts as a problem, which files matter, and whether modeling is appropriate. A smaller question creates a result you can check before committing to more work.', 'Try “Find missing values and repeated rows in this dataset, and explain which columns need attention. Do not fit a model yet.” This names the input, task, output, and boundary. You can judge whether the answer did what you asked.'] },
    { title: 'Make the context explicit', paragraphs: ['Tell the assistant what one row represents and which column, if any, is the prediction target. If observations share a batch, laboratory, source paper, or experimental family, explain that relationship. Those details influence what a fair evaluation looks like.', 'Attach only the relevant materials. In a continuing project, check the selected file chips before sending a follow-up. Context is useful when it applies to the question at hand.'] },
    { title: 'Use the plan as a conversation', paragraphs: ['Turn on plan review for an unfamiliar or expensive investigation. Look for an understandable connection between the goal, the proposed tools, and the expected evidence. Ask for a narrower plan if that connection is unclear.', 'After the first step, inspect the saved results. Then ask the next question the evidence supports. Iteration is valuable when each step reduces a real uncertainty.'] },
  ] },
  { slug: 'a-score-needs-a-split', title: 'A model score is only as useful as its split.', description: 'Why the boundary between training and test data belongs in the research question.', category: 'Research notes', art: 'wave', cover: 'lattice', guide: 'audit-and-evaluation', sections: [
    { title: 'Decide what “new” means', paragraphs: ['Predicting another measurement from a familiar batch is a different task from predicting a new material family. Both can matter, but they require different evidence. A score without a description of the holdout leaves that distinction unresolved.', 'Before selecting a model, write down the future case you want to understand. That statement should guide how observations are kept apart.'] },
    { title: 'Look beyond row identity', paragraphs: ['Different row identifiers do not guarantee independent observations. Samples can share preparation conditions, a source publication, or a time period. Related information crossing the train–test boundary can make performance look stronger than the intended use warrants.', 'Audit the data, identify meaningful grouping columns, and inspect a split’s actual membership. Choose from the installed strategies according to the scientific question rather than accepting a default without review.'] },
    { title: 'Preserve the comparison', paragraphs: ['Compare supported baselines with the same inputs and evaluation conditions. Keep model selection separate from the final test, and record when test results were exposed. Once a result influences a choice, it is part of the experimental history.', 'Report the metric with its scope: the held-out population, sample count, units, and limitations. This makes the number useful to someone deciding whether it answers their question.'] },
  ] },
  { slug: 'keep-evidence-with-the-answer', title: 'Keep the evidence close to the answer.', description: 'A practical habit for reviewing AI-assisted research and preserving what comes next.', category: 'Workflow', art: 'prism', cover: 'archive', guide: 'evidence-and-reports', sections: [
    { title: 'Read the reference, not just the citation', paragraphs: ['An answer can sound precise while leaving an important assumption unstated. Open the referenced passage and compare its actual scope with the claim. Does it describe the same material, conditions, measurement, or population?', 'Document extraction is imperfect. If a table, equation, or figure matters, inspect the original PDF. A reference makes a claim easier to review; it does not make that review unnecessary.'] },
    { title: 'Follow a result back to its inputs', paragraphs: ['For a numerical result, inspect the dataset, split, configuration, and saved output. These are part of the explanation. A short answer can be useful at the surface while the supporting record preserves the detail.', 'Use the project’s provenance to keep derived work connected. When inputs or assumptions change, preserve the distinction between the old experiment and the new one.'] },
    { title: 'Leave a useful record', paragraphs: ['Unsuccessful attempts are worth keeping when they explain what was tested and why the next step changed. Record the conditions and limits of the lesson so that a later investigation can assess whether it applies.', 'When you export, capture settled work as a fixed report snapshot. The goal is a record another researcher can inspect, question, and build on.'] },
  ] },
];

export function readingMinutes(sections: GuideSection[]) {
  return Math.max(1, Math.ceil(sections.flatMap(s => [s.title, ...s.paragraphs, ...(s.steps ?? []), s.note ?? '']).join(' ').split(/\s+/).length / 200));
}
export const sectionId = (title: string) => title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-$/, '');
